# Generated by Django 2.2 on 2020-09-04 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200904_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.DynamicMenu'),
        ),
    ]
